name: Auto Deploy to GitHub Pages Repo

on:
  workflow_run:
    workflows:
      - "Build Signed Native APK"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Clone target repo
        run: |
          # Yahan GH_PAT use ho raha hai
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.TARGET_REPO }} target
      - name: Sync files
        run: |
         rsync -av --delete \
         --exclude ".git" \
         --exclude ".github" \
         --exclude "target" \
         ./ target/
      - name: Check copied files
        run: |
         ls -la
         ls -la target
         git status
         
      - name: Restore CNAME
        run: |
          echo "rsh.gdsnotes.in" > target/CNAME
      - name: Show target changes
        run: |
         cd target
         git status
         git diff --stat
          
      - name: Commit and Push
        run: |
          cd target
          git add .
          git commit -m "Auto update from gdsnotes" || echo "No changes to commit"
          git push
          
